### ISSUE TITLE
在(3)中‘演示并说明僵尸进程的出现，并演示僵尸进程的危害’  中僵尸进程并未出现

### ISSUE THREAD

**Issue by flymenn** [elarity/advanced-php#1]
本地环境ubuntu16.06 +php7.2 
按照例子并未出现 标识为[Z+] 的 僵尸进程。

**Comment by elarity** [comment]
注意使用 ps -aux | grep 'keyword' 的时候，使用php作为关键字，如果用进程名称grep的话，一旦子进程成了僵尸进程，grep进程名称是grep不到的，只能通过grep php来获取到，你再试试
