### ISSUE TITLE
进程daemon化样例中的判断有问题

### ISSUE THREAD

**Issue by pengwenwu** [elarity/advanced-php#31]
```
// 将当前子进程提升会会话组组长 这是至关重要的一步 
if ( ! posix_setsid() ) {
    exit( ' setsid error. ' );
}
```
这个地方的判断是不是应该是posix_setsid()<0, [官方文档](http://php.net/manual/zh/function.posix-setsid.php)上说：`错误时返回-1`。

另外：这个样例里，为什么需要二次fork？麻烦指导一下

**Comment by jingmian** [comment]
为了保证形成的daemon进程绝对不会成为会话首进程，不会拥有控制终端。简白来说,就是让程序不会意外出错

**Comment by wangzhaobo168** [comment]
还是功力不够啊,虽然我也不懂,但是我搜了一下. 感觉有帮助, 你可以看看这个https://www.jianshu.com/p/161d9981112a

**Comment by pengwenwu** [comment]
> 还是功力不够啊,虽然我也不懂,但是我搜了一下. 感觉有帮助, 你可以看看这个https://www.jianshu.com/p/161d9981112a

非常感谢

**Comment by pengwenwu** [comment]
> 为了保证形成的daemon进程绝对不会成为会话首进程，不会拥有控制终端。简白来说,就是让程序不会意外出错

非常感谢
