### ISSUE TITLE
李哥，请教个14章里的代码问题，就是我改了下代码,客户端telnet发送quit后,服务端关闭这个链接，这个客户端再连接时，发送的消息服务端接收不到了，代码和演示在下面

### ISSUE THREAD

**Issue by hkui** [elarity/advanced-php#34]
server.php
`<?php
$host = '0.0.0.0';
$port = 9999;
$fd = socket_create( AF_INET, SOCK_STREAM, SOL_TCP );
socket_bind( $fd, $host, $port );
socket_listen( $fd );
// 注意，将“监听socket”设置为非阻塞模式
socket_set_nonblock( $fd );

$event_arr = [];
$conn_arr = [];

echo PHP_EOL.PHP_EOL."欢迎来到ti-chat聊天室!发言注意遵守当地法律法规!".PHP_EOL;
echo "        tcp://{$host}:{$port}".PHP_EOL;

$event_base = new EventBase();

$event = new Event( $event_base, $fd, Event::READ | Event::PERSIST, function( $fd )
{
    // 使用全局的event_arr 和 conn_arr
    global $event_arr,$conn_arr,$event_base;
    // 非阻塞模式下，注意accpet的写法会稍微特殊一些。如果不想这么写，请往前面添加@符号，不过不建议这种写法
    if( ( $conn = socket_accept( $fd ) ) != false ){
        echo date('Y-m-d H:i:s').'：欢迎'.intval( $conn ).'来到聊天室'.PHP_EOL;
        // 将连接socket也设置为非阻塞模式
        socket_set_nonblock( $conn );
        // 此处值得注意，我们需要将连接socket保存到数组中去
        $conn_arr[ intval( $conn ) ] = $conn;
        $event = new Event( $event_base, $conn, Event::READ | Event::PERSIST, function( $conn ) use( $event_arr )
        {
            global $conn_arr;
            $buffer = trim(socket_read( $conn, 65535 ));
            $msg = intval( $conn ).'说 : '.$buffer.PHP_EOL;
            if($buffer=='quit'){
                unset($conn_arr[intval($conn)]);
                unset($event_arr[intval($conn)]);
                socket_close($conn);
                $buffer="我 走了";
                $msg = intval( $conn ).'说 : '.$buffer.PHP_EOL;
            }
            echo $msg.PHP_EOL;
            foreach( $conn_arr as $conn_key => $conn_item ){
                if( $conn != $conn_item ){
                    socket_write( $conn_item, $msg, strlen( $msg ) );
                }
            }
            if($buffer=='quit'){
                unset($conn);
            }
        }, $conn );
        $event->add();
        // 此处值得注意，我们需要将事件本身存储到全局数组中，如果不保存，连接会话会丢失，也就是说服务端和客户端将无法保持持久会话
        $event_arr[ intval( $conn ) ] = $event;
    }
}, $fd );
$event->add();
$event_base->loop();`

演示:
![problem](https://user-images.githubusercontent.com/4144760/58364076-0cdc0d00-7ee1-11e9-8801-b5bbe66f942f.gif)

疑问:图中的6发送quit到server,server断开了连接，然后在这个客户端窗口再次连接产生7，然后发送消息，为何server和其它客户端都接收不到7的消息了呢，其它客户端发的消息，它能正常收到，需要调整哪里呢？

**Comment by elarity** [comment]
有时间我看下哈

**Comment by hkui** [comment]
找到原因了，最里面一层的 unset($event_arr[intval($conn)]);没起作用，要么global $event_arr进去，要么引用传值，改成下面就就好了
```
<?php
$host = '0.0.0.0';
$port = 8071;
$fd = socket_create( AF_INET, SOCK_STREAM, SOL_TCP );
socket_set_option($fd, SOL_SOCKET, SO_REUSEADDR, 1);
socket_bind( $fd, $host, $port );
socket_listen( $fd );

socket_set_nonblock( $fd );

$event_arr = [];
$conn_arr = [];

echo PHP_EOL.PHP_EOL."欢迎来到ti-chat聊天室!发言注意遵守当地法律法规!".PHP_EOL;
echo "        tcp://{$host}:{$port}".PHP_EOL;

$event_base = new EventBase();

$event = new Event( $event_base, $fd, Event::READ | Event::PERSIST, function( $fd )
{
    // 使用全局的event_arr 和 conn_arr
    global $event_arr,$conn_arr,$event_base;
    // 非阻塞模式下，注意accpet的写法会稍微特殊一些。如果不想这么写，请往前面添加@符号，不过不建议这种写法
    if( ( $conn = socket_accept( $fd ) ) != false ){
        echo date('Y-m-d H:i:s').'：欢迎'.intval( $conn ).'来到聊天室'.PHP_EOL;
        socket_set_nonblock( $conn );
        $conn_arr[ intval( $conn ) ] = $conn;
        $event = new Event( $event_base, $conn, Event::READ | Event::PERSIST, function( $conn )
        {
            global $conn_arr;
            global $event_arr;
            $buffer = trim(socket_read( $conn, 65535 ));
            $msg = intval( $conn ).' say : '.$buffer.PHP_EOL;
            if($buffer=='quit'){
                unset($conn_arr[intval($conn)]);
                unset($event_arr[intval($conn)]);
                socket_close($conn);
                $buffer="Good bye!";
                $msg = intval( $conn ).' say : '.$buffer.PHP_EOL;
            }

            echo $msg.PHP_EOL;
            //向其它连接的用户发消息
            foreach( $conn_arr as $conn_key => $conn_item ){
                if( $conn != $conn_item ){
                    socket_write( $conn_item, $msg, strlen( $msg ) );
                }
            }

        }, $conn );

        $event->add();
        $event_arr[ intval( $conn ) ] = $event;
    }
}, $fd );

$event->add();
$event_base->loop();
```
