### ISSUE TITLE
关于 php xxx.php &  关闭终端会退出

### ISSUE THREAD

**Issue by CaoDongDong1991** [elarity/advanced-php#5]
首先，感谢你的知识分享，我想请教一个问题
你提到一个知识点是，单独的在命令后面加 & 符号 在终端退出的时候，进程也会推到
我的环境是：本地虚拟机+xshell 
当我在xshell中用命令启动进程后，我立即关闭xshell，这个时候我的程序还在跑。
我就有点懵逼了。还请先生指点一二。

**Comment by elarity** [comment]
明白，我没有用ssh之类的远程连接到服务器上，而是直接本地操作。不过这个没什么好纠结的，这个原理就是你关闭或者退出终端会向其发送sighup或者是其它什么信号，然后进程收到这个信号后会有默认行为，默认行为大多都是退出。远程连接的我回去试一下，可能确如你所说。究其原因，就是xshell没有发送信号或者发送的信号被进程忽略了，多做几次测试就好了，没什么好纠结的。用&终究不是可靠的方案。
